CREATE DATABASE LandCompany;
GO
--DROP DATABASE LandCompany
--GO
USE master;
USE LandCompany;
GO

CREATE TABLE UsageType (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Tax REAL DEFAULT(0) NOT NULL
)
GO

ALTER TABLE UsageType
ADD CONSTRAINT CH_UsageType_Tax CHECK (Tax >= 0)
GO

CREATE TABLE Location (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Address VARCHAR(50) NOT NULL UNIQUE,
	Tax REAL DEFAULT(0) NOT NULL
)
GO

ALTER TABLE Location
ADD CONSTRAINT CH_Location_Tax CHECK (Tax >= 0)
GO

CREATE TABLE Resource (
	ID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NULL,
	Tax REAL DEFAULT(0) NOT NULL
)
GO

ALTER TABLE Resource
ADD CONSTRAINT CH_Resource_Tax CHECK (Tax >= 0)
GO

CREATE TABLE Natural (
	ID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
	Surname VARCHAR(20) NOT NULL,
    DBDate DATE NOT NULL,
	Phone VARCHAR(15) NOT NULL UNIQUE
)
GO

ALTER TABLE Natural
ADD CONSTRAINT CH_Natural_Name 
CHECK (Name NOT LIKE '%[^A-Za-z'' -]%')
GO

ALTER TABLE Natural
ADD CONSTRAINT CH_Natural_Surname 
CHECK (Surname NOT LIKE '%[^A-Za-z'' -]%')
GO

ALTER TABLE Natural
ADD CONSTRAINT CH_Natural_DBDate 
CHECK (DBDate LIKE '____-__-__' AND DBDate NOT LIKE '%[a-Z]%')
GO

ALTER TABLE Natural
ADD CONSTRAINT CH_Natural_Phone 
CHECK (Phone LIKE '___-___-____' AND Phone NOT LIKE '%[a-Z]%')
GO

CREATE TABLE Registrar (
	ID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
	Surname VARCHAR(20) NOT NULL,
    Phone VARCHAR(15) NOT NULL UNIQUE
)
GO

ALTER TABLE Registrar
ADD CONSTRAINT CH_Registrar_Name 
CHECK (Name NOT LIKE '%[^A-Za-z'' -]%')
GO

ALTER TABLE Registrar
ADD CONSTRAINT CH_Registrar_Surname 
CHECK (Surname NOT LIKE '%[^A-Za-z'' -]%')
GO

ALTER TABLE Registrar
ADD CONSTRAINT CH_Registrar_Phone 
CHECK (Phone LIKE '___-___-____' AND Phone NOT LIKE '%[a-Z]%')
GO

--DROP TABLE Legal 
CREATE TABLE Legal (
	ID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
	FkNaturalID INT NOT NULL
)
GO

ALTER TABLE Legal
WITH CHECK ADD CONSTRAINT FK_Natural_ID FOREIGN KEY(FkNaturalID)
REFERENCES Natural(ID)
ON UPDATE CASCADE 
ON DELETE CASCADE
GO

CREATE TABLE Land (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FkOwnerID INT NULL,
	FkLocationID INT NOT NULL,
	FkUsageTypeID INt NULL
)
GO

ALTER TABLE Land
WITH CHECK ADD CONSTRAINT FK_Owner_ID FOREIGN KEY(FkOwnerID)
REFERENCES Natural(ID)
ON UPDATE CASCADE
GO

ALTER TABLE Land
WITH CHECK ADD CONSTRAINT FK_Location_ID FOREIGN KEY(FkLocationID)
REFERENCES Location(ID)
ON UPDATE CASCADE 
ON DELETE CASCADE
GO

ALTER TABLE Land
WITH CHECK ADD CONSTRAINT FK_UsageType_ID FOREIGN KEY(FkUsageTypeID)
REFERENCES UsageType(ID)
ON UPDATE CASCADE 
ON DELETE SET NULL
GO

CREATE TABLE Utility (
	FkLandID INT NULL,
	Plumbing BIT DEFAULT(0) NOT NULL,
	Sanitation BIT DEFAULT(0) NOT NULL,
	Heating BIT DEFAULT(0) NOT NULL,
	Gas BIT DEFAULT(0) NOT NULL
)
GO

ALTER TABLE Utility
WITH CHECK ADD CONSTRAINT FK_Land_ID FOREIGN KEY(FkLandID)
REFERENCES Land(ID)
ON UPDATE CASCADE 
ON DELETE SET NULL
GO

--DROP TABLE Object
CREATE TABLE Object (
	FkLandID INT NOT NULL,
	FkResourceID INT NULL,
	LatitudeLU REAL NOT NULL,
	LatitudeRL REAL NOT NULL,
	LongtitudeLU REAL NOT NULL,
	LongtitudeRL REAL NOT NULL
)
GO

ALTER TABLE Object
WITH CHECK ADD CONSTRAINT FK_Object_Land_ID FOREIGN KEY(FkLandID)
REFERENCES Land(ID)
ON UPDATE CASCADE 
ON DELETE CASCADE
GO

ALTER TABLE Object
WITH CHECK ADD CONSTRAINT FK_Resource_ID FOREIGN KEY(FkResourceID)
REFERENCES Resource(ID)
ON UPDATE CASCADE 
ON DELETE SET NULL
GO

ALTER TABLE Object
ADD CONSTRAINT CH_Latitude CHECK (LatitudeLU < LatitudeRL)
GO

ALTER TABLE Object
ADD CONSTRAINT CH_Longtitude CHECK (LongtitudeLU < LongtitudeRL)
GO

--DROP TABLE Act
CREATE TABLE Act (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FkLandID INT NOT NULL,
	FkBuyerID INT NOT NULL,
	FkSellerID INT NOT NULL,
	FkRegistrarID INT NOT NULL,
	Date DATE NOT NULL
)
GO

ALTER TABLE Act
WITH CHECK ADD CONSTRAINT FK_Act_Land_ID FOREIGN KEY(FkLandID)
REFERENCES Land(ID)
ON UPDATE CASCADE
GO

ALTER TABLE Act
WITH CHECK ADD CONSTRAINT FK_Buyer_ID FOREIGN KEY(FkBuyerID)
REFERENCES Natural(ID)
ON DELETE NO ACTION
GO

ALTER TABLE Act
WITH CHECK ADD CONSTRAINT FK_Seller_ID FOREIGN KEY(FkSellerID)
REFERENCES Natural(ID)
ON DELETE NO ACTION
GO

ALTER TABLE Act
WITH CHECK ADD CONSTRAINT FK_Registrar_ID FOREIGN KEY(FkRegistrarID)
REFERENCES Registrar(ID)
ON UPDATE CASCADE
ON DELETE NO ACTION
GO