USE master;
USE LandCompany;
GO

insert into Location (Address, Tax) values ('8787 Cambridge Alley', 4.13);
insert into Location (Address, Tax) values ('55735 Menomonie Hill', 3.39);
insert into Location (Address, Tax) values ('0 3rd Street', 0.91);
insert into Location (Address, Tax) values ('828 Monterey Alley', 1.14);
insert into Location (Address, Tax) values ('85032 Rigney Alley', 4.89);
insert into Location (Address, Tax) values ('93694 Pierstorff Point', 1.77);
insert into Location (Address, Tax) values ('39 Westend Pass', 3.05);
insert into Location (Address, Tax) values ('8 Charing Cross Circle', 3.8);
insert into Location (Address, Tax) values ('335 Northport Lane', 2.99);
insert into Location (Address, Tax) values ('4821 Loftsgordon Junction', 3.48);
insert into Location (Address, Tax) values ('2 Gateway Plaza', 2.59);
insert into Location (Address, Tax) values ('2985 Cody Center', 2.35);
insert into Location (Address, Tax) values ('48389 Marquette Alley', 3.83);
insert into Location (Address, Tax) values ('6109 2nd Drive', 1.08);
insert into Location (Address, Tax) values ('9119 Farragut Junction', 2.3);
insert into Location (Address, Tax) values ('0895 Little Fleur Street', 4.41);
insert into Location (Address, Tax) values ('6273 Debra Street', 0.46);
insert into Location (Address, Tax) values ('7 Lotheville Lane', 4.84);
insert into Location (Address, Tax) values ('4107 Thompson Park', 1.82);
insert into Location (Address, Tax) values ('3980 Stuart Crossing', 0.08);
insert into Location (Address, Tax) values ('454 Basil Center', 5.85);
insert into Location (Address, Tax) values ('3089 Di Loreto Park', 7.68);
insert into Location (Address, Tax) values ('28 Sutherland Junction', 2.02);
insert into Location (Address, Tax) values ('4265 Moland Pass', 7.27);
insert into Location (Address, Tax) values ('6 Sage Crossing', 2.89);
insert into Location (Address, Tax) values ('496 Reindahl Lane', 8.23);
insert into Location (Address, Tax) values ('94307 Almo Street', 4.57);
insert into Location (Address, Tax) values ('4 Farwell Drive', 7.14);
insert into Location (Address, Tax) values ('7118 Hoepker Point', 9.54);
insert into Location (Address, Tax) values ('38 Sunnyside Court', 5.51);
insert into Location (Address, Tax) values ('360 Union Parkway', 5.08);
insert into Location (Address, Tax) values ('44469 Rusk Circle', 2.43);
insert into Location (Address, Tax) values ('42 Nelson Point', 4.16);
insert into Location (Address, Tax) values ('70 Mallard Street', 2.97);
insert into Location (Address, Tax) values ('1 Donald Park', 4.13);
insert into Location (Address, Tax) values ('28647 Cherokee Hill', 4.46);
insert into Location (Address, Tax) values ('61864 Calypso Street', 6.31);
insert into Location (Address, Tax) values ('9109 Roth Lane', 2.46);
insert into Location (Address, Tax) values ('756 Brentwood Way', 6.83);
insert into Location (Address, Tax) values ('6 Grover Alley', 2.2);
insert into Location (Address, Tax) values ('929 Coolidge Court', 8.03);
insert into Location (Address, Tax) values ('5281 Fairfield Circle', 7.7);
insert into Location (Address, Tax) values ('94 Upham Road', 1.06);
insert into Location (Address, Tax) values ('670 Rieder Junction', 4.02);
insert into Location (Address, Tax) values ('71 Melrose Road', 1.35);
insert into Location (Address, Tax) values ('44454 Ridge Oak Hill', 5.55);
insert into Location (Address, Tax) values ('3479 Burning Wood Avenue', 5.01);
insert into Location (Address, Tax) values ('6 Farragut Crossing', 6.22);
insert into Location (Address, Tax) values ('6391 Pierstorff Circle', 1.17);
insert into Location (Address, Tax) values ('95 Graedel Place', 7.56);
insert into Location (Address, Tax) values ('603 Toban Park', 5.05);
insert into Location (Address, Tax) values ('8 Fallview Terrace', 4.98);
insert into Location (Address, Tax) values ('5 Sachtjen Center', 8.15);
insert into Location (Address, Tax) values ('41 Mcguire Point', 9.66);
insert into Location (Address, Tax) values ('8275 Forest Dale Park', 7.68);
insert into Location (Address, Tax) values ('540 Texas Center', 2.33);
insert into Location (Address, Tax) values ('5784 Esker Place', 2.28);
insert into Location (Address, Tax) values ('2196 Moland Park', 8.27);
insert into Location (Address, Tax) values ('7237 Warbler Point', 8.89);
insert into Location (Address, Tax) values ('049 Rieder Road', 1.87);
insert into Location (Address, Tax) values ('9495 Vahlen Way', 5.0);
insert into Location (Address, Tax) values ('52 Atwood Center', 1.9);
insert into Location (Address, Tax) values ('54 Washington Avenue', 7.73);
insert into Location (Address, Tax) values ('350 Warbler Street', 2.38);
insert into Location (Address, Tax) values ('2 Melody Street', 8.26);
insert into Location (Address, Tax) values ('355 Grayhawk Trail', 8.53);
insert into Location (Address, Tax) values ('4759 Debra Road', 3.12);
insert into Location (Address, Tax) values ('0 Schlimgen Street', 9.72);
insert into Location (Address, Tax) values ('406 Prentice Trail', 7.21);
insert into Location (Address, Tax) values ('805 Twin Pines Place', 4.18);
insert into Location (Address, Tax) values ('5 Vahlen Terrace', 4.22);