use master;
use LandCompany;
go

insert into Resource (FkObjectID, Name, Tax) values (21, 'lectus suspendisse potenti', 1.33);
insert into Resource (FkObjectID, Name, Tax) values (26, 'aenean lectus', 2.73);
insert into Resource (FkObjectID, Name, Tax) values (38, 'convallis morbi', 1.66);
insert into Resource (FkObjectID, Name, Tax) values (9, 'non lectus aliquam sit amet', 2.66);
insert into Resource (FkObjectID, Name, Tax) values (23, 'cubilia curae duis faucibus accumsan', 1.42);
insert into Resource (FkObjectID, Name, Tax) values (42, 'ut suscipit a', 1.07);
insert into Resource (FkObjectID, Name, Tax) values (43, 'quis orci nullam molestie nibh', 2.64);
insert into Resource (FkObjectID, Name, Tax) values (16, 'tristique fusce', 1.59);
insert into Resource (FkObjectID, Name, Tax) values (31, 'integer ac', 2.4);
insert into Resource (FkObjectID, Name, Tax) values (35, 'duis bibendum morbi', 2.97);
insert into Resource (FkObjectID, Name, Tax) values (20, 'malesuada in imperdiet', 1.24);
insert into Resource (FkObjectID, Name, Tax) values (24, 'in', 1.28);
insert into Resource (FkObjectID, Name, Tax) values (22, 'donec posuere metus vitae ipsum', 1.19);
insert into Resource (FkObjectID, Name, Tax) values (3, 'dui proin', 2.18);
insert into Resource (FkObjectID, Name, Tax) values (1, 'nibh in lectus pellentesque at', 2.73);
insert into Resource (FkObjectID, Name, Tax) values (7, 'curabitur', 1.32);
insert into Resource (FkObjectID, Name, Tax) values (12, 'placerat praesent blandit', 1.23);
insert into Resource (FkObjectID, Name, Tax) values (6, 'sapien', 1.06);
insert into Resource (FkObjectID, Name, Tax) values (12, 'cubilia curae', 2.13);
insert into Resource (FkObjectID, Name, Tax) values (3, 'bibendum morbi non quam nec', 2.3);
insert into Resource (FkObjectID, Name, Tax) values (25, 'pellentesque', 2.59);
insert into Resource (FkObjectID, Name, Tax) values (24, 'nulla', 2.53);
insert into Resource (FkObjectID, Name, Tax) values (19, 'amet sapien dignissim vestibulum vestibulum', 2.28);
insert into Resource (FkObjectID, Name, Tax) values (2, 'laoreet ut rhoncus aliquet pulvinar', 2.43);
insert into Resource (FkObjectID, Name, Tax) values (32, 'eu interdum eu tincidunt in', 2.41);
insert into Resource (FkObjectID, Name, Tax) values (12, 'blandit ultrices enim lorem ipsum', 2.72);
insert into Resource (FkObjectID, Name, Tax) values (16, 'nulla tempus vivamus', 2.1);
insert into Resource (FkObjectID, Name, Tax) values (15, 'ligula sit amet eleifend pede', 1.4);
insert into Resource (FkObjectID, Name, Tax) values (42, 'sagittis sapien cum sociis natoque', 2.1);
insert into Resource (FkObjectID, Name, Tax) values (13, 'parturient montes nascetur', 1.96);
insert into Resource (FkObjectID, Name, Tax) values (22, 'suspendisse potenti nullam porttitor', 2.56);
insert into Resource (FkObjectID, Name, Tax) values (23, 'nisi vulputate', 2.82);
insert into Resource (FkObjectID, Name, Tax) values (14, 'odio consequat varius', 2.61);
insert into Resource (FkObjectID, Name, Tax) values (24, 'sodales scelerisque mauris sit amet', 2.11);
insert into Resource (FkObjectID, Name, Tax) values (7, 'vestibulum ante ipsum', 2.98);
insert into Resource (FkObjectID, Name, Tax) values (7, 'sapien varius ut blandit non', 2.69);
insert into Resource (FkObjectID, Name, Tax) values (14, 'lacus morbi', 1.17);
insert into Resource (FkObjectID, Name, Tax) values (1, 'nec molestie', 1.08);
insert into Resource (FkObjectID, Name, Tax) values (18, 'dolor', 1.67);
insert into Resource (FkObjectID, Name, Tax) values (7, 'cras mi pede malesuada in', 2.84);
insert into Resource (FkObjectID, Name, Tax) values (6, 'donec semper sapien a', 1.63);
insert into Resource (FkObjectID, Name, Tax) values (24, 'lacus curabitur', 2.0);
insert into Resource (FkObjectID, Name, Tax) values (16, 'dignissim vestibulum vestibulum ante ipsum', 2.55);
insert into Resource (FkObjectID, Name, Tax) values (5, 'congue diam id', 1.99);
insert into Resource (FkObjectID, Name, Tax) values (2, 'amet', 1.87);
insert into Resource (FkObjectID, Name, Tax) values (3, 'parturient montes', 1.53);
insert into Resource (FkObjectID, Name, Tax) values (24, 'at diam nam', 2.83);
insert into Resource (FkObjectID, Name, Tax) values (9, 'potenti cras in', 2.15);
insert into Resource (FkObjectID, Name, Tax) values (2, 'convallis nulla neque libero', 1.32);
insert into Resource (FkObjectID, Name, Tax) values (23, 'pharetra magna ac', 2.32);
insert into Resource (FkObjectID, Name, Tax) values (18, 'malesuada in imperdiet', 1.54);
insert into Resource (FkObjectID, Name, Tax) values (15, 'pede ullamcorper augue a', 1.53);
insert into Resource (FkObjectID, Name, Tax) values (15, 'interdum in ante', 2.98);
insert into Resource (FkObjectID, Name, Tax) values (14, 'porta', 1.97);
insert into Resource (FkObjectID, Name, Tax) values (22, 'nullam varius nulla facilisi cras', 1.79);
insert into Resource (FkObjectID, Name, Tax) values (41, 'natoque penatibus', 1.67);
insert into Resource (FkObjectID, Name, Tax) values (1, 'morbi', 1.12);
insert into Resource (FkObjectID, Name, Tax) values (2, 'tempus vivamus in', 2.67);
insert into Resource (FkObjectID, Name, Tax) values (1, 'nunc', 2.78);
insert into Resource (FkObjectID, Name, Tax) values (9, 'tortor id nulla ultrices aliquet', 2.13);
insert into Resource (FkObjectID, Name, Tax) values (15, 'eros', 1.01);
insert into Resource (FkObjectID, Name, Tax) values (4, 'primis in faucibus', 2.4);
insert into Resource (FkObjectID, Name, Tax) values (5, 'nulla ac enim in tempor', 2.37);
insert into Resource (FkObjectID, Name, Tax) values (15, 'risus dapibus', 1.07);
insert into Resource (FkObjectID, Name, Tax) values (5, 'eleifend', 1.26);
insert into Resource (FkObjectID, Name, Tax) values (1, 'volutpat in congue etiam', 1.54);
insert into Resource (FkObjectID, Name, Tax) values (5, 'habitasse platea dictumst etiam', 1.56);
insert into Resource (FkObjectID, Name, Tax) values (4, 'vestibulum ante ipsum primis in', 2.77);
insert into Resource (FkObjectID, Name, Tax) values (10, 'in leo maecenas pulvinar lobortis', 1.72);
insert into Resource (FkObjectID, Name, Tax) values (5, 'quam suspendisse potenti nullam', 1.79);
insert into Resource (FkObjectID, Name, Tax) values (7, 'aliquam sit amet diam', 2.73);
insert into Resource (FkObjectID, Name, Tax) values (11, 'convallis eget', 1.65);
insert into Resource (FkObjectID, Name, Tax) values (5, 'ac consequat metus sapien', 2.33);
insert into Resource (FkObjectID, Name, Tax) values (1, 'turpis adipiscing lorem vitae mattis', 1.27);
insert into Resource (FkObjectID, Name, Tax) values (14, 'congue', 1.92);
insert into Resource (FkObjectID, Name, Tax) values (37, 'cursus id turpis', 2.2);
insert into Resource (FkObjectID, Name, Tax) values (24, 'lacus at turpis donec posuere', 2.28);
insert into Resource (FkObjectID, Name, Tax) values (12, 'penatibus et magnis dis parturient', 2.81);
insert into Resource (FkObjectID, Name, Tax) values (38, 'sed accumsan felis', 2.15);
insert into Resource (FkObjectID, Name, Tax) values (12, 'pede posuere', 2.92);
insert into Resource (FkObjectID, Name, Tax) values (4, 'elit', 2.43);
insert into Resource (FkObjectID, Name, Tax) values (43, 'eleifend donec ut', 1.61);
insert into Resource (FkObjectID, Name, Tax) values (2, 'vel accumsan tellus', 2.88);
insert into Resource (FkObjectID, Name, Tax) values (28, 'varius nulla facilisi cras non', 2.46);
insert into Resource (FkObjectID, Name, Tax) values (11, 'luctus cum', 2.42);
insert into Resource (FkObjectID, Name, Tax) values (8, 'rhoncus mauris', 1.77);
insert into Resource (FkObjectID, Name, Tax) values (25, 'eget elit sodales scelerisque', 2.25);
insert into Resource (FkObjectID, Name, Tax) values (4, 'nisi venenatis tristique fusce congue', 2.64);
insert into Resource (FkObjectID, Name, Tax) values (14, 'convallis duis consequat dui nec', 1.03);
insert into Resource (FkObjectID, Name, Tax) values (1, 'aliquam erat volutpat in congue', 1.63);
insert into Resource (FkObjectID, Name, Tax) values (17, 'convallis', 2.52);
insert into Resource (FkObjectID, Name, Tax) values (14, 'diam in', 2.37);
insert into Resource (FkObjectID, Name, Tax) values (26, 'cum sociis natoque penatibus', 2.75);
insert into Resource (FkObjectID, Name, Tax) values (38, 'nascetur ridiculus mus', 1.19);
insert into Resource (FkObjectID, Name, Tax) values (9, 'lectus aliquam sit amet', 2.73);
insert into Resource (FkObjectID, Name, Tax) values (29, 'dapibus', 2.37);
insert into Resource (FkObjectID, Name, Tax) values (30, 'integer ac leo pellentesque', 2.82);
insert into Resource (FkObjectID, Name, Tax) values (33, 'tortor eu pede', 1.62);
insert into Resource (FkObjectID, Name, Tax) values (41, 'elementum pellentesque quisque', 1.86);
insert into Resource (FkObjectID, Name, Tax) values (7, 'metus aenean fermentum donec', 2.53);
insert into Resource (FkObjectID, Name, Tax) values (4, 'id', 2.49);
insert into Resource (FkObjectID, Name, Tax) values (34, 'amet eleifend pede', 2.23);
insert into Resource (FkObjectID, Name, Tax) values (25, 'erat fermentum justo nec condimentum', 1.71);
insert into Resource (FkObjectID, Name, Tax) values (31, 'erat id mauris', 2.7);
insert into Resource (FkObjectID, Name, Tax) values (27, 'adipiscing', 2.98);
insert into Resource (FkObjectID, Name, Tax) values (19, 'tortor quis turpis', 1.44);
insert into Resource (FkObjectID, Name, Tax) values (22, 'dignissim vestibulum vestibulum ante', 1.68);
insert into Resource (FkObjectID, Name, Tax) values (10, 'erat', 2.81);
insert into Resource (FkObjectID, Name, Tax) values (7, 'et commodo vulputate justo in', 2.08);
insert into Resource (FkObjectID, Name, Tax) values (21, 'eget elit sodales', 2.86);
insert into Resource (FkObjectID, Name, Tax) values (36, 'tincidunt', 2.32);
insert into Resource (FkObjectID, Name, Tax) values (6, 'potenti cras in', 2.38);
insert into Resource (FkObjectID, Name, Tax) values (25, 'velit donec diam', 1.44);
insert into Resource (FkObjectID, Name, Tax) values (21, 'eget tincidunt eget tempus', 2.81);
insert into Resource (FkObjectID, Name, Tax) values (8, 'sapien dignissim vestibulum', 2.46);
insert into Resource (FkObjectID, Name, Tax) values (17, 'nec sem', 2.44);
insert into Resource (FkObjectID, Name, Tax) values (15, 'luctus', 1.14);
insert into Resource (FkObjectID, Name, Tax) values (8, 'est et tempus', 1.84);
insert into Resource (FkObjectID, Name, Tax) values (16, 'felis', 2.94);
insert into Resource (FkObjectID, Name, Tax) values (24, 'diam id ornare imperdiet sapien', 2.39);
insert into Resource (FkObjectID, Name, Tax) values (9, 'vestibulum aliquet ultrices erat tortor', 1.71);
insert into Resource (FkObjectID, Name, Tax) values (1, 'sapien varius ut blandit', 1.58);
insert into Resource (FkObjectID, Name, Tax) values (6, 'orci luctus et ultrices', 1.72);
insert into Resource (FkObjectID, Name, Tax) values (4, 'amet sapien dignissim vestibulum', 1.95);
insert into Resource (FkObjectID, Name, Tax) values (26, 'praesent blandit lacinia', 2.33);
insert into Resource (FkObjectID, Name, Tax) values (11, 'nec dui luctus rutrum', 2.67);
insert into Resource (FkObjectID, Name, Tax) values (22, 'lacus curabitur', 2.97);
insert into Resource (FkObjectID, Name, Tax) values (23, 'interdum eu tincidunt', 2.01);
insert into Resource (FkObjectID, Name, Tax) values (9, 'sit amet justo morbi', 2.69);
insert into Resource (FkObjectID, Name, Tax) values (10, 'mauris laoreet ut', 2.16);
insert into Resource (FkObjectID, Name, Tax) values (12, 'interdum venenatis turpis', 2.99);
insert into Resource (FkObjectID, Name, Tax) values (24, 'vulputate elementum nullam varius', 2.85);
insert into Resource (FkObjectID, Name, Tax) values (4, 'eget tincidunt eget tempus', 1.02);
insert into Resource (FkObjectID, Name, Tax) values (43, 'sem praesent', 1.43);
insert into Resource (FkObjectID, Name, Tax) values (1, 'consequat', 1.23);
insert into Resource (FkObjectID, Name, Tax) values (6, 'ac', 2.45);
insert into Resource (FkObjectID, Name, Tax) values (5, 'ac', 1.82);
insert into Resource (FkObjectID, Name, Tax) values (21, 'sed justo pellentesque viverra', 2.84);
insert into Resource (FkObjectID, Name, Tax) values (20, 'in quam', 2.65);
insert into Resource (FkObjectID, Name, Tax) values (16, 'in quam', 2.03);
insert into Resource (FkObjectID, Name, Tax) values (8, 'ipsum integer a', 1.81);
insert into Resource (FkObjectID, Name, Tax) values (17, 'ac nibh fusce', 1.09);
insert into Resource (FkObjectID, Name, Tax) values (9, 'eleifend luctus', 2.89);
insert into Resource (FkObjectID, Name, Tax) values (19, 'dolor sit amet consectetuer adipiscing', 1.96);
insert into Resource (FkObjectID, Name, Tax) values (8, 'eleifend luctus ultricies', 1.11);
insert into Resource (FkObjectID, Name, Tax) values (12, 'convallis eget eleifend', 2.11);
insert into Resource (FkObjectID, Name, Tax) values (14, 'turpis adipiscing lorem', 2.39);
insert into Resource (FkObjectID, Name, Tax) values (23, 'ut blandit non interdum', 1.05);
insert into Resource (FkObjectID, Name, Tax) values (14, 'ligula pellentesque ultrices', 1.69);
insert into Resource (FkObjectID, Name, Tax) values (17, 'vel est donec odio justo', 2.05);
insert into Resource (FkObjectID, Name, Tax) values (35, 'erat fermentum', 2.45);
insert into Resource (FkObjectID, Name, Tax) values (14, 'vestibulum proin eu mi', 1.76);
insert into Resource (FkObjectID, Name, Tax) values (30, 'dolor', 1.26);
insert into Resource (FkObjectID, Name, Tax) values (23, 'morbi sem', 2.1);
insert into Resource (FkObjectID, Name, Tax) values (13, 'consequat varius', 1.63);
insert into Resource (FkObjectID, Name, Tax) values (4, 'quis orci', 2.68);
insert into Resource (FkObjectID, Name, Tax) values (3, 'cras pellentesque volutpat dui', 1.27);
insert into Resource (FkObjectID, Name, Tax) values (1, 'quisque arcu', 1.92);
insert into Resource (FkObjectID, Name, Tax) values (1, 'faucibus', 2.85);
insert into Resource (FkObjectID, Name, Tax) values (3, 'integer', 1.18);
insert into Resource (FkObjectID, Name, Tax) values (30, 'nisi volutpat eleifend donec ut', 1.17);
insert into Resource (FkObjectID, Name, Tax) values (16, 'amet eros suspendisse accumsan tortor', 2.26);
insert into Resource (FkObjectID, Name, Tax) values (29, 'condimentum neque sapien placerat', 1.24);
insert into Resource (FkObjectID, Name, Tax) values (3, 'turpis', 2.45);
insert into Resource (FkObjectID, Name, Tax) values (4, 'maecenas rhoncus aliquam', 1.97);
insert into Resource (FkObjectID, Name, Tax) values (16, 'pede venenatis non sodales', 1.27);
insert into Resource (FkObjectID, Name, Tax) values (22, 'dui', 2.19);
insert into Resource (FkObjectID, Name, Tax) values (13, 'pretium quis lectus suspendisse potenti', 1.12);
insert into Resource (FkObjectID, Name, Tax) values (20, 'quisque', 1.39);
insert into Resource (FkObjectID, Name, Tax) values (8, 'aenean sit amet justo morbi', 2.19);
insert into Resource (FkObjectID, Name, Tax) values (5, 'sem fusce', 2.62);
insert into Resource (FkObjectID, Name, Tax) values (18, 'habitasse platea', 1.25);
insert into Resource (FkObjectID, Name, Tax) values (23, 'suspendisse potenti nullam porttitor lacus', 2.18);
insert into Resource (FkObjectID, Name, Tax) values (9, 'tristique tortor eu pede', 1.19);
insert into Resource (FkObjectID, Name, Tax) values (13, 'proin eu mi nulla', 2.17);
insert into Resource (FkObjectID, Name, Tax) values (5, 'adipiscing lorem vitae', 1.24);
insert into Resource (FkObjectID, Name, Tax) values (4, 'dis parturient montes', 2.16);
insert into Resource (FkObjectID, Name, Tax) values (25, 'viverra pede ac diam', 2.12);
insert into Resource (FkObjectID, Name, Tax) values (3, 'dolor quis odio consequat varius', 2.48);
insert into Resource (FkObjectID, Name, Tax) values (14, 'purus aliquet at feugiat', 1.53);
insert into Resource (FkObjectID, Name, Tax) values (43, 'fermentum justo nec condimentum neque', 2.48);
insert into Resource (FkObjectID, Name, Tax) values (29, 'nibh ligula nec', 2.35);
insert into Resource (FkObjectID, Name, Tax) values (3, 'quam a odio in', 1.41);
insert into Resource (FkObjectID, Name, Tax) values (11, 'odio', 2.78);
insert into Resource (FkObjectID, Name, Tax) values (36, 'in magna bibendum imperdiet', 1.19);
insert into Resource (FkObjectID, Name, Tax) values (23, 'eros suspendisse accumsan tortor', 1.71);
insert into Resource (FkObjectID, Name, Tax) values (36, 'curae mauris viverra diam vitae', 1.89);
insert into Resource (FkObjectID, Name, Tax) values (43, 'faucibus', 1.02);
insert into Resource (FkObjectID, Name, Tax) values (4, 'cubilia curae duis', 1.14);
insert into Resource (FkObjectID, Name, Tax) values (13, 'ut nunc vestibulum', 1.55);
insert into Resource (FkObjectID, Name, Tax) values (12, 'vitae', 1.9);
insert into Resource (FkObjectID, Name, Tax) values (17, 'a libero nam dui proin', 2.22);
insert into Resource (FkObjectID, Name, Tax) values (17, 'cubilia curae nulla', 1.4);
insert into Resource (FkObjectID, Name, Tax) values (33, 'dapibus duis at', 1.03);
insert into Resource (FkObjectID, Name, Tax) values (19, 'praesent blandit', 1.32);
insert into Resource (FkObjectID, Name, Tax) values (16, 'massa', 2.37);
insert into Resource (FkObjectID, Name, Tax) values (3, 'cras non', 2.11);
insert into Resource (FkObjectID, Name, Tax) values (31, 'libero rutrum ac lobortis vel', 2.3);
insert into Resource (FkObjectID, Name, Tax) values (2, 'rhoncus sed vestibulum', 2.96);
insert into Resource (FkObjectID, Name, Tax) values (15, 'quisque arcu', 2.01);
insert into Resource (FkObjectID, Name, Tax) values (26, 'amet diam in magna bibendum', 2.02);
insert into Resource (FkObjectID, Name, Tax) values (8, 'id turpis integer aliquet massa', 2.68);
insert into Resource (FkObjectID, Name, Tax) values (16, 'velit donec diam neque vestibulum', 1.46);
insert into Resource (FkObjectID, Name, Tax) values (7, 'mauris', 2.91);
insert into Resource (FkObjectID, Name, Tax) values (19, 'augue aliquam erat volutpat in', 2.09);
insert into Resource (FkObjectID, Name, Tax) values (11, 'sapien ut nunc vestibulum', 1.15);
insert into Resource (FkObjectID, Name, Tax) values (20, 'praesent', 1.72);
insert into Resource (FkObjectID, Name, Tax) values (4, 'platea dictumst', 1.56);
insert into Resource (FkObjectID, Name, Tax) values (33, 'nulla pede ullamcorper', 1.14);
insert into Resource (FkObjectID, Name, Tax) values (10, 'nulla elit', 1.18);
insert into Resource (FkObjectID, Name, Tax) values (13, 'sociis natoque', 1.11);
insert into Resource (FkObjectID, Name, Tax) values (25, 'nisl duis', 2.8);
insert into Resource (FkObjectID, Name, Tax) values (5, 'et tempus semper', 1.6);
insert into Resource (FkObjectID, Name, Tax) values (20, 'cursus id turpis integer', 1.95);
insert into Resource (FkObjectID, Name, Tax) values (13, 'lectus', 2.42);
insert into Resource (FkObjectID, Name, Tax) values (20, 'leo', 2.76);
insert into Resource (FkObjectID, Name, Tax) values (16, 'nam congue risus semper porta', 1.01);
insert into Resource (FkObjectID, Name, Tax) values (21, 'justo in blandit', 1.13);
insert into Resource (FkObjectID, Name, Tax) values (16, 'risus', 2.76);
insert into Resource (FkObjectID, Name, Tax) values (7, 'vivamus', 1.16);
insert into Resource (FkObjectID, Name, Tax) values (37, 'eu nibh', 1.73);
insert into Resource (FkObjectID, Name, Tax) values (6, 'tempus', 1.29);
insert into Resource (FkObjectID, Name, Tax) values (23, 'cras in purus eu', 1.85);
insert into Resource (FkObjectID, Name, Tax) values (12, 'congue diam id', 1.04);
insert into Resource (FkObjectID, Name, Tax) values (14, 'fermentum justo', 2.62);
insert into Resource (FkObjectID, Name, Tax) values (23, 'laoreet', 1.05);
insert into Resource (FkObjectID, Name, Tax) values (22, 'at dolor quis', 2.76);
insert into Resource (FkObjectID, Name, Tax) values (1, 'semper rutrum', 1.43);
insert into Resource (FkObjectID, Name, Tax) values (4, 'nec dui luctus rutrum', 1.82);
insert into Resource (FkObjectID, Name, Tax) values (6, 'in purus eu magna vulputate', 1.18);
insert into Resource (FkObjectID, Name, Tax) values (11, 'luctus et', 2.67);
insert into Resource (FkObjectID, Name, Tax) values (25, 'sem fusce consequat nulla', 2.43);
insert into Resource (FkObjectID, Name, Tax) values (21, 'dis', 2.03);
insert into Resource (FkObjectID, Name, Tax) values (15, 'velit eu est congue', 2.97);
insert into Resource (FkObjectID, Name, Tax) values (6, 'vel nulla eget eros', 1.1);
insert into Resource (FkObjectID, Name, Tax) values (37, 'aliquam quis turpis', 2.39);
insert into Resource (FkObjectID, Name, Tax) values (13, 'at', 2.13);
insert into Resource (FkObjectID, Name, Tax) values (6, 'aliquam', 1.37);
insert into Resource (FkObjectID, Name, Tax) values (16, 'felis sed lacus morbi', 1.98);
insert into Resource (FkObjectID, Name, Tax) values (33, 'leo pellentesque ultrices', 1.48);
insert into Resource (FkObjectID, Name, Tax) values (13, 'vivamus vel nulla eget', 1.13);
insert into Resource (FkObjectID, Name, Tax) values (19, 'sit', 1.39);
insert into Resource (FkObjectID, Name, Tax) values (23, 'ipsum dolor', 1.87);
insert into Resource (FkObjectID, Name, Tax) values (9, 'pellentesque viverra pede ac diam', 1.8);
insert into Resource (FkObjectID, Name, Tax) values (25, 'at', 1.27);
insert into Resource (FkObjectID, Name, Tax) values (17, 'nam dui proin leo', 2.12);
insert into Resource (FkObjectID, Name, Tax) values (1, 'blandit non interdum in', 2.22);
insert into Resource (FkObjectID, Name, Tax) values (14, 'penatibus et', 2.66);
insert into Resource (FkObjectID, Name, Tax) values (7, 'vestibulum', 2.15);
insert into Resource (FkObjectID, Name, Tax) values (19, 'nisi eu orci mauris lacinia', 2.26);
insert into Resource (FkObjectID, Name, Tax) values (21, 'mattis', 1.13);
insert into Resource (FkObjectID, Name, Tax) values (3, 'erat', 1.23);
insert into Resource (FkObjectID, Name, Tax) values (17, 'imperdiet nullam orci pede', 2.18);
insert into Resource (FkObjectID, Name, Tax) values (13, 'nisi', 2.51);
insert into Resource (FkObjectID, Name, Tax) values (13, 'in', 2.64);
insert into Resource (FkObjectID, Name, Tax) values (18, 'sed lacus', 2.57);
insert into Resource (FkObjectID, Name, Tax) values (20, 'lorem vitae mattis', 2.44);
insert into Resource (FkObjectID, Name, Tax) values (32, 'dolor', 2.88);
insert into Resource (FkObjectID, Name, Tax) values (12, 'dui nec', 2.67);
insert into Resource (FkObjectID, Name, Tax) values (23, 'nisl duis bibendum felis', 1.05);
insert into Resource (FkObjectID, Name, Tax) values (43, 'sapien', 1.99);
insert into Resource (FkObjectID, Name, Tax) values (2, 'vulputate ut ultrices vel augue', 2.13);
insert into Resource (FkObjectID, Name, Tax) values (20, 'fusce posuere felis', 1.35);
insert into Resource (FkObjectID, Name, Tax) values (1, 'ac lobortis', 2.69);
insert into Resource (FkObjectID, Name, Tax) values (35, 'quis odio consequat varius integer', 2.77);
insert into Resource (FkObjectID, Name, Tax) values (6, 'donec', 2.1);
insert into Resource (FkObjectID, Name, Tax) values (13, 'a libero nam dui', 2.23);
insert into Resource (FkObjectID, Name, Tax) values (14, 'sit amet', 2.33);
insert into Resource (FkObjectID, Name, Tax) values (21, 'quisque ut erat curabitur gravida', 1.03);
insert into Resource (FkObjectID, Name, Tax) values (8, 'mauris laoreet', 1.93);
insert into Resource (FkObjectID, Name, Tax) values (14, 'dui proin leo', 2.19);
insert into Resource (FkObjectID, Name, Tax) values (16, 'lectus pellentesque eget', 1.82);
insert into Resource (FkObjectID, Name, Tax) values (40, 'vitae', 2.19);
insert into Resource (FkObjectID, Name, Tax) values (9, 'ac leo pellentesque', 1.78);
insert into Resource (FkObjectID, Name, Tax) values (5, 'tincidunt lacus at', 2.55);
insert into Resource (FkObjectID, Name, Tax) values (5, 'enim in tempor', 2.12);
insert into Resource (FkObjectID, Name, Tax) values (17, 'turpis elementum ligula vehicula', 1.42);
insert into Resource (FkObjectID, Name, Tax) values (9, 'erat eros viverra', 1.86);
insert into Resource (FkObjectID, Name, Tax) values (11, 'morbi', 1.11);
insert into Resource (FkObjectID, Name, Tax) values (19, 'duis faucibus', 1.86);
insert into Resource (FkObjectID, Name, Tax) values (9, 'primis in faucibus', 2.85);
insert into Resource (FkObjectID, Name, Tax) values (30, 'elementum nullam varius nulla facilisi', 1.06);
insert into Resource (FkObjectID, Name, Tax) values (41, 'fringilla rhoncus mauris enim', 1.59);
insert into Resource (FkObjectID, Name, Tax) values (17, 'mauris vulputate', 1.15);
insert into Resource (FkObjectID, Name, Tax) values (7, 'ultrices posuere cubilia curae duis', 1.15);
insert into Resource (FkObjectID, Name, Tax) values (23, 'tincidunt eu felis fusce', 1.89);
insert into Resource (FkObjectID, Name, Tax) values (14, 'quisque', 1.31);
insert into Resource (FkObjectID, Name, Tax) values (2, 'lorem ipsum dolor', 1.87);
insert into Resource (FkObjectID, Name, Tax) values (33, 'eu nibh', 2.76);
insert into Resource (FkObjectID, Name, Tax) values (24, 'vitae consectetuer', 2.4);
insert into Resource (FkObjectID, Name, Tax) values (11, 'purus eu magna vulputate luctus', 2.06);
insert into Resource (FkObjectID, Name, Tax) values (13, 'ut erat id mauris vulputate', 2.11);
insert into Resource (FkObjectID, Name, Tax) values (5, 'cras', 1.88);
insert into Resource (FkObjectID, Name, Tax) values (11, 'et eros vestibulum', 1.5);
insert into Resource (FkObjectID, Name, Tax) values (41, 'semper interdum mauris ullamcorper purus', 2.94);
insert into Resource (FkObjectID, Name, Tax) values (22, 'diam id ornare imperdiet sapien', 2.23);
insert into Resource (FkObjectID, Name, Tax) values (24, 'viverra pede', 1.25);
insert into Resource (FkObjectID, Name, Tax) values (14, 'turpis', 1.66);
insert into Resource (FkObjectID, Name, Tax) values (4, 'potenti in eleifend', 2.74);
insert into Resource (FkObjectID, Name, Tax) values (37, 'lectus pellentesque eget', 2.95);
