USE master;
USE LandCompany;
GO

insert into UsageType (Name, Tax) values ('convallis nunc proin at turpis', 2.84);
insert into UsageType (Name, Tax) values ('morbi non quam nec dui luctus', 3.3);
insert into UsageType (Name, Tax) values ('morbi odio odio', 4.55);
insert into UsageType (Name, Tax) values ('orci luctus et ultrices posuere', 0.18);
insert into UsageType (Name, Tax) values ('leo odio condimentum id luctus nec molestie sed', 1.02);
insert into UsageType (Name, Tax) values ('non mauris morbi non lectus aliquam sit', 3.47);
insert into UsageType (Name, Tax) values ('orci nullam molestie nibh in', 2.87);
insert into UsageType (Name, Tax) values ('justo morbi ut odio', 1.05);
insert into UsageType (Name, Tax) values ('luctus et ultrices posuere cubilia curae duis', 3.56);
insert into UsageType (Name, Tax) values ('natoque penatibus et', 4.09);
insert into UsageType (Name, Tax) values ('neque aenean auctor gravida sem praesent', 1.12);
insert into UsageType (Name, Tax) values ('mollis molestie lorem quisque', 2.65);
insert into UsageType (Name, Tax) values ('est donec odio justo sollicitudin ut suscipit a', 2.76);
insert into UsageType (Name, Tax) values ('leo pellentesque ultrices donec vitae nisi', 1.25);
insert into UsageType (Name, Tax) values ('vitae nisi nam ultrices', 4.6);
insert into UsageType (Name, Tax) values ('in felis eu sapien cursus vestibulum proin', 4.16);
insert into UsageType (Name, Tax) values ('vel nisl duis ac nibh fusce lacus', 3.91);
insert into UsageType (Name, Tax) values ('accumsan odio curabitur convallis dui', 2.72);
insert into UsageType (Name, Tax) values ('congue diam id ornare imperdiet pretium', 3.72);
insert into UsageType (Name, Tax) values ('metus vitae ipsum aliquam', 1.88);
insert into UsageType (Name, Tax) values ('in blandit ultrices enim', 6.5);
insert into UsageType (Name, Tax) values ('in', 4.64);
insert into UsageType (Name, Tax) values ('nunc', 7.18);
insert into UsageType (Name, Tax) values ('aliquet ultrices', 4.88);
insert into UsageType (Name, Tax) values ('faucibus orci', 5.29);
insert into UsageType (Name, Tax) values ('consequat', 9.98);
insert into UsageType (Name, Tax) values ('erat nulla tempus vivamus in', 7.65);
insert into UsageType (Name, Tax) values ('faucibus', 9.61);
insert into UsageType (Name, Tax) values ('congue', 2.72);
insert into UsageType (Name, Tax) values ('nullam porttitor', 8.73);
insert into UsageType (Name, Tax) values ('morbi vestibulum velit id', 3.7);
insert into UsageType (Name, Tax) values ('porttitor lorem', 9.77);
insert into UsageType (Name, Tax) values ('maecenas tristique', 8.46);
insert into UsageType (Name, Tax) values ('sit', 8.1);
insert into UsageType (Name, Tax) values ('ligula pellentesque ultrices phasellus id', 1.12);
insert into UsageType (Name, Tax) values ('aliquet pulvinar sed nisl', 6.53);
insert into UsageType (Name, Tax) values ('cubilia curae nulla', 5.76);
insert into UsageType (Name, Tax) values ('est quam pharetra magna', 4.19);
insert into UsageType (Name, Tax) values ('metus sapien ut nunc', 7.39);
insert into UsageType (Name, Tax) values ('pharetra magna', 6.16);
insert into UsageType (Name, Tax) values ('orci eget', 1.42);
insert into UsageType (Name, Tax) values ('at feugiat non', 2.16);
insert into UsageType (Name, Tax) values ('nibh', 4.96);
insert into UsageType (Name, Tax) values ('nec', 4.56);
insert into UsageType (Name, Tax) values ('vestibulum vestibulum', 9.55);
insert into UsageType (Name, Tax) values ('integer', 4.06);
insert into UsageType (Name, Tax) values ('cras', 9.69);
insert into UsageType (Name, Tax) values ('eget', 4.21);
insert into UsageType (Name, Tax) values ('integer a nibh in', 1.18);
insert into UsageType (Name, Tax) values ('metus', 8.71);
insert into UsageType (Name, Tax) values ('id', 3.31);
insert into UsageType (Name, Tax) values ('orci pede venenatis non sodales', 4.15);
insert into UsageType (Name, Tax) values ('ultrices libero non', 4.34);
insert into UsageType (Name, Tax) values ('vel accumsan tellus', 6.34);
insert into UsageType (Name, Tax) values ('sed accumsan felis ut', 3.92);
insert into UsageType (Name, Tax) values ('turpis sed ante vivamus tortor', 7.36);
insert into UsageType (Name, Tax) values ('velit', 1.01);
insert into UsageType (Name, Tax) values ('pede ac diam', 6.69);
insert into UsageType (Name, Tax) values ('libero convallis eget', 5.92);
insert into UsageType (Name, Tax) values ('gravida nisi at', 1.84);
insert into UsageType (Name, Tax) values ('id consequat in consequat ut', 6.48);
insert into UsageType (Name, Tax) values ('dui vel sem', 9.96);
insert into UsageType (Name, Tax) values ('massa', 6.61);
insert into UsageType (Name, Tax) values ('porttitor', 5.0);
insert into UsageType (Name, Tax) values ('nullam sit amet turpis', 1.19);
insert into UsageType (Name, Tax) values ('rutrum nulla nunc', 1.89);
insert into UsageType (Name, Tax) values ('dapibus augue', 2.24);
insert into UsageType (Name, Tax) values ('sapien quis libero nullam', 2.47);
insert into UsageType (Name, Tax) values ('rhoncus dui vel sem sed', 8.24);
insert into UsageType (Name, Tax) values ('convallis eget eleifend', 4.15);
insert into UsageType (Name, Tax) values ('sapien arcu', 8.2);
insert into UsageType (Name, Tax) values ('leo odio condimentum', 1.92);
insert into UsageType (Name, Tax) values ('in ante vestibulum ante ipsum', 4.82);
insert into UsageType (Name, Tax) values ('volutpat quam pede lobortis ligula', 6.72);
insert into UsageType (Name, Tax) values ('vehicula condimentum curabitur', 6.69);
insert into UsageType (Name, Tax) values ('duis consequat dui nec', 6.87);
insert into UsageType (Name, Tax) values ('sem fusce consequat', 7.97);
insert into UsageType (Name, Tax) values ('tortor', 6.93);
insert into UsageType (Name, Tax) values ('luctus et ultrices posuere cubilia', 2.52);
insert into UsageType (Name, Tax) values ('vivamus', 1.7);
insert into UsageType (Name, Tax) values ('vitae quam suspendisse potenti', 2.19);
insert into UsageType (Name, Tax) values ('accumsan tortor quis turpis', 8.3);
insert into UsageType (Name, Tax) values ('nisi nam ultrices', 8.39);
insert into UsageType (Name, Tax) values ('morbi a ipsum integer a', 3.05);
insert into UsageType (Name, Tax) values ('id', 1.94);